version: 2

project_name: maily

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: maily
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X maily/internal/version.Version={{.Version}}
      - -X maily/internal/version.Commit={{.Commit}}
      - -X maily/internal/version.Date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: guiyumin
    name: maily
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - repository:
      owner: guiyumin
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/guiyumin/maily"
    description: "A terminal email client for Gmail"
    license: "MIT"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "{{ .ProjectName }}: update to {{ .Tag }}"
