import { invoke } from "@tauri-apps/api/core";
import type { Tag, EmailTag } from "@/types/tags";

// Tag CRUD operations

export async function listTags(): Promise<Tag[]> {
  return invoke<Tag[]>("list_tags");
}

export async function createTag(name: string, color: string): Promise<Tag> {
  return invoke<Tag>("create_tag", { name, color });
}

export async function deleteTag(tagId: number): Promise<void> {
  return invoke("delete_tag", { tagId });
}

// Email-Tag operations

export async function getEmailTags(
  account: string,
  mailbox: string,
  uid: number
): Promise<EmailTag[]> {
  return invoke<EmailTag[]>("get_email_tags", { account, mailbox, uid });
}

export async function addEmailTag(
  account: string,
  mailbox: string,
  uid: number,
  tagId: number,
  autoGenerated: boolean = false
): Promise<void> {
  return invoke("add_email_tag", {
    account,
    mailbox,
    uid,
    tagId,
    autoGenerated,
  });
}

export async function removeEmailTag(
  account: string,
  mailbox: string,
  uid: number,
  tagId: number
): Promise<void> {
  return invoke("remove_email_tag", { account, mailbox, uid, tagId });
}

export async function getBatchEmailTags(
  account: string,
  mailbox: string,
  uids: number[]
): Promise<Record<number, EmailTag[]>> {
  return invoke<Record<number, EmailTag[]>>("get_batch_email_tags", {
    account,
    mailbox,
    uids,
  });
}

// Search by tags

export async function searchEmailsByTags(
  account: string,
  mailbox: string,
  tagIds: number[]
): Promise<number[]> {
  return invoke<number[]>("search_emails_by_tags", {
    account,
    mailbox,
    tagIds,
  });
}
