/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailAccountMailboxUidRouteImport } from './routes/email.$account.$mailbox.$uid'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountMailboxUidRoute = EmailAccountMailboxUidRouteImport.update({
  id: '/email/$account/$mailbox/$uid',
  path: '/email/$account/$mailbox/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/email/$account/$mailbox/$uid': typeof EmailAccountMailboxUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/email/$account/$mailbox/$uid': typeof EmailAccountMailboxUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/email/$account/$mailbox/$uid': typeof EmailAccountMailboxUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/email/$account/$mailbox/$uid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/email/$account/$mailbox/$uid'
  id: '__root__' | '/' | '/settings' | '/email/$account/$mailbox/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  EmailAccountMailboxUidRoute: typeof EmailAccountMailboxUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/$account/$mailbox/$uid': {
      id: '/email/$account/$mailbox/$uid'
      path: '/email/$account/$mailbox/$uid'
      fullPath: '/email/$account/$mailbox/$uid'
      preLoaderRoute: typeof EmailAccountMailboxUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  EmailAccountMailboxUidRoute: EmailAccountMailboxUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
